
export const ADVERTISING_STYLES: string[] = [
    "Create a photorealistic, 4K resolution advertising image for a cosmetic/fashion product. The image should feature the provided model in a minimalist, clean studio setting with soft, diffused lighting. The model's face must be preserved exactly as in the photo. The product must be clearly and sharply visible. The final image must be 600x600 pixels.",
    "Create a photorealistic, 4K resolution advertising image for a cosmetic/fashion product. The image should feature the provided model in a luxurious, high-fashion magazine style with dramatic shadows and a sophisticated, dark background. The model's face must be preserved exactly as in the photo. The product must be clearly and sharply visible. The final image must be 600x600 pixels.",
    "Create a photorealistic, 4K resolution advertising image for a cosmetic/fashion product. The image should feature the provided model in a vibrant, outdoor urban street style setting, with dynamic city lights in the background. The model's face must be preserved exactly as in the photo. The product must be clearly and sharply visible. The final image must be 600x600 pixels.",
    "Create a photorealistic, 4K resolution advertising image for a cosmetic/fashion product. The image should feature the provided model in a natural, serene outdoor setting, like a sun-drenched beach or a lush garden at golden hour. The model's face must be preserved exactly as in the photo. The product must be clearly and sharply visible. The final image must be 600x600 pixels.",
    "Create a photorealistic, 4K resolution advertising image for a cosmetic/fashion product. The image should feature the provided model in a futuristic, neon-lit cyberpunk theme. The aesthetic should be edgy and modern. The model's face must be preserved exactly as in the photo. The product must be clearly and sharply visible. The final image must be 600x600 pixels.",
    "Create a photorealistic, 4K resolution advertising image for a cosmetic/fashion product. The image should be in an elegant and classic black and white photography style, with high contrast and emotional depth. The model's face must be preserved exactly as in the photo. The product must be clearly and sharply visible. The final image must be 600x600 pixels."
];
